pub(crate) mod analysis;
pub(crate) mod anti_patterns;
pub(crate) mod context;
pub(crate) mod deps;
mod deslop;
pub(crate) mod doctor;
pub(crate) mod duplicates;
pub(crate) mod exceptions;
pub(crate) mod globals;
pub(crate) mod graph;
mod metrics;
pub(crate) mod naming;
pub(crate) mod searchability;
pub(crate) mod side_effects;
pub(crate) mod singletons;
mod stats;
pub(crate) mod todos;
pub(crate) mod unreferenced;
pub(crate) mod wildcards;

pub(crate) use analysis::handle_analysis;
pub(crate) use anti_patterns::{handle_anti_patterns, AntiPatternsFlags};
pub(crate) use context::{handle_context, ContextFlags};
pub(crate) use deps::{handle_deps, DepsCliArgs, DepsFlags};
pub(crate) use deslop::handle_deslop;
pub(crate) use doctor::{handle_doctor, DoctorFlags};
pub(crate) use duplicates::{handle_duplicates, DuplicatesFlags};
pub(crate) use exceptions::{handle_exceptions, ExceptionsFlags};
pub(crate) use globals::{handle_globals, GlobalsFlags};
pub(crate) use graph::{handle_graph, GraphFlags};
pub(crate) use metrics::{handle_cc, handle_hal, handle_mi, handle_raw, CcFlags, MiFlags};
pub(crate) use naming::{handle_naming, NamingFlags};
pub(crate) use searchability::{handle_searchability, SearchabilityFlags};
pub(crate) use side_effects::{handle_side_effects, SideEffectsFlags};
pub(crate) use singletons::{handle_singletons, SingletonsFlags};
pub(crate) use stats::{handle_files, handle_stats};
pub(crate) use todos::{handle_todos, TodosFlags};
pub(crate) use unreferenced::{handle_unreferenced, UnreferencedFlags};
pub(crate) use wildcards::{handle_wildcards, WildcardsFlags};
