use crate::rules::ids;

use super::{rule, RuleCategory, RuleDescriptor, RuleSeverity, DOC_QUALITY};

pub(crate) static QUALITY_RULES: &[RuleDescriptor] = &[
    rule(
        ids::RULE_ID_MUTABLE_DEFAULT,
        RuleCategory::Quality,
        RuleSeverity::Medium,
        DOC_QUALITY,
    ),
    rule(
        ids::RULE_ID_BARE_EXCEPT,
        RuleCategory::Quality,
        RuleSeverity::Medium,
        DOC_QUALITY,
    ),
    rule(
        ids::RULE_ID_DANGEROUS_COMPARISON,
        RuleCategory::Quality,
        RuleSeverity::Low,
        DOC_QUALITY,
    ),
    rule(
        ids::RULE_ID_COMPLEXITY,
        RuleCategory::Quality,
        RuleSeverity::Medium,
        DOC_QUALITY,
    ),
    rule(
        ids::RULE_ID_NESTING,
        RuleCategory::Quality,
        RuleSeverity::Medium,
        DOC_QUALITY,
    ),
    rule(
        ids::RULE_ID_MIN_MI,
        RuleCategory::Quality,
        RuleSeverity::Medium,
        DOC_QUALITY,
    ),
    rule(
        ids::RULE_ID_COGNITIVE_COMPLEXITY,
        RuleCategory::Quality,
        RuleSeverity::Medium,
        DOC_QUALITY,
    ),
    rule(
        ids::RULE_ID_COHESION,
        RuleCategory::Quality,
        RuleSeverity::Low,
        DOC_QUALITY,
    ),
    rule(
        ids::RULE_ID_ARGUMENT_COUNT,
        RuleCategory::Quality,
        RuleSeverity::Low,
        DOC_QUALITY,
    ),
    rule(
        ids::RULE_ID_FUNCTION_LENGTH,
        RuleCategory::Quality,
        RuleSeverity::Low,
        DOC_QUALITY,
    ),
    rule(
        ids::RULE_ID_MEMBERSHIP_LIST,
        RuleCategory::Quality,
        RuleSeverity::Low,
        DOC_QUALITY,
    ),
    rule(
        ids::RULE_ID_FILE_READ_RISK,
        RuleCategory::Quality,
        RuleSeverity::Low,
        DOC_QUALITY,
    ),
    rule(
        ids::RULE_ID_STRING_CONCAT,
        RuleCategory::Quality,
        RuleSeverity::Low,
        DOC_QUALITY,
    ),
    rule(
        ids::RULE_ID_USELESS_CAST,
        RuleCategory::Quality,
        RuleSeverity::Low,
        DOC_QUALITY,
    ),
    rule(
        ids::RULE_ID_REGEX_LOOP,
        RuleCategory::Quality,
        RuleSeverity::Low,
        DOC_QUALITY,
    ),
    rule(
        ids::RULE_ID_ATTRIBUTE_HOIST,
        RuleCategory::Quality,
        RuleSeverity::Low,
        DOC_QUALITY,
    ),
    rule(
        ids::RULE_ID_PURE_CALL_HOIST,
        RuleCategory::Quality,
        RuleSeverity::Low,
        DOC_QUALITY,
    ),
    rule(
        ids::RULE_ID_EXCEPTION_FLOW_LOOP,
        RuleCategory::Quality,
        RuleSeverity::Low,
        DOC_QUALITY,
    ),
    rule(
        ids::RULE_ID_DICT_ITERATOR,
        RuleCategory::Quality,
        RuleSeverity::Low,
        DOC_QUALITY,
    ),
    rule(
        ids::RULE_ID_GLOBAL_LOOP,
        RuleCategory::Quality,
        RuleSeverity::Low,
        DOC_QUALITY,
    ),
    rule(
        ids::RULE_ID_MEMORYVIEW_BYTES,
        RuleCategory::Quality,
        RuleSeverity::Low,
        DOC_QUALITY,
    ),
    rule(
        ids::RULE_ID_TUPLE_OVER_LIST,
        RuleCategory::Quality,
        RuleSeverity::Low,
        DOC_QUALITY,
    ),
    rule(
        ids::RULE_ID_COMPREHENSION,
        RuleCategory::Quality,
        RuleSeverity::Low,
        DOC_QUALITY,
    ),
    rule(
        ids::RULE_ID_PANDAS_CHUNK_RISK,
        RuleCategory::Quality,
        RuleSeverity::Low,
        DOC_QUALITY,
    ),
];
